export const FETCH_DICTIONARY_START = 'FETCH_DICTIONARY_START';
export const FETCH_DICTIONARY_SUCCESS = 'FETCH_DICTIONARY_SUCCESS';
export const FETCH_DICTIONARY_FAIL = 'FETCH_DICTIONARY_FAIL';

export const SAVE_DICTIONARY_START = 'SAVE_DICTIONARY_START';
export const SAVE_DICTIONARY_SUCCESS = 'SAVE_DICTIONARY_SUCCESS';
export const SAVE_DICTIONARY_FAIL = 'SAVE_DICTIONARY_FAIL';
export const SAVE_DICTIONARY_CLEANUP = 'SAVE_DICTIONARY_CLEANUP';

export const FETCH_DICTIONARY_LIST_START = 'FETCH_DICTIONARY_LIST_START';
export const FETCH_DICTIONARY_LIST_SUCCESS = 'FETCH_DICTIONARY_LIST_SUCCESS';
export const FETCH_DICTIONARY_LIST_FAIL = 'FETCH_DICTIONARY_LIST_FAIL';

export const DELETE_DICTIONARY_SUCCESS = 'DELETE_DICTIONARY_SUCCESS';
export const DELETE_DICTIONARY_FAIL = 'DELETE_DICTIONARY_FAIL';